import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers as ChakraProvider } from "./chakraProvider";
import Providers from "./queryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <Providers>{children}</Providers>
        </ChakraProvider>
      </body>
    </html>
  );
}
